<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('siap_mhs', function (Blueprint $table) {
            $table->char('nim', 16)->primary();
            $table->smallInteger('id_kategori_spp')->default(0)->index('id_kategori_spp');
            $table->char('kelas', 3)->default('0');
            $table->decimal('nilai_masuk', 4)->default(0);
            $table->char('thn_ak_masuk', 5)->nullable()->index('thn_ak_masuk');
            $table->char('thn_ak_lulus', 5)->nullable();
            $table->char('nama_mhs', 145);
            $table->string('nik_mhs')->default('0');
            $table->string('nisn');
            $table->string('npwp')->default('0');
            $table->char('id_status_awal', 1)->nullable();
            $table->integer('id_status_aktif_mhs')->default(0)->index('id_status_aktif_mhs');
            $table->char('id_status_mhs', 1)->default('');
            $table->tinyInteger('id_prodi')->index('id_prodi');
            $table->smallInteger('id_pegawai')->nullable()->default(0);
            $table->smallInteger('operator')->nullable();
            $table->char('jk', 1)->nullable();
            $table->char('golongan_darah', 2)->default('0');
            $table->char('warga_negara', 3)->nullable();
            $table->string('kebangsaan', 50)->nullable();
            $table->string('tempat_lahir', 50)->nullable();
            $table->date('tgl_lahir')->nullable();
            $table->tinyInteger('id_agama')->nullable();
            $table->char('id_status_sipil', 1)->nullable();
            $table->string('alamat')->nullable();
            $table->string('kota', 100)->default('0');
            $table->string('kode_pos', 6)->nullable();
            $table->char('id_wil', 8)->index('id_wil');
            $table->string('nama_kelurahan');
            $table->char('id_kabupaten', 10)->default('0');
            $table->char('id_prov', 2)->default('0');
            $table->char('id_kab', 4)->default('0');
            $table->char('id_kec', 6)->default('0');
            $table->char('id_kel', 10)->nullable()->default('0');
            $table->string('telepon', 50)->nullable();
            $table->string('handphone', 50)->nullable();
            $table->string('email', 100)->nullable();
            $table->string('alamat_asal')->nullable();
            $table->string('kota_asal', 100)->default('0');
            $table->char('id_kabupaten_asal', 10)->default('0');
            $table->char('id_prov_asal', 2)->default('0');
            $table->char('id_kab_asal', 4)->default('0');
            $table->char('id_kec_asal', 6)->default('0');
            $table->char('id_kel_asal', 10)->nullable()->default('0');
            $table->char('kode_pos_asal', 6)->nullable();
            $table->string('negara_asal', 50)->nullable();
            $table->string('nama_ayah', 50)->nullable();
            $table->string('nik_ayah')->default('0');
            $table->tinyInteger('id_agama_ayah')->nullable();
            $table->char('id_pendidikan_ayah', 2)->nullable();
            $table->char('id_pekerjaan_ayah', 1)->nullable();
            $table->char('id_status_hidup_ayah', 1)->nullable();
            $table->string('nama_ibu', 50)->nullable();
            $table->string('nik_ibu')->default('0');
            $table->tinyInteger('id_agama_ibu')->nullable();
            $table->char('id_pendidikan_ibu', 2)->nullable();
            $table->char('id_pekerjaan_ibu', 1)->nullable();
            $table->char('id_status_hidup_ibu', 1)->nullable();
            $table->integer('penghasilan_ortu')->default(0);
            $table->integer('penghasilan_ayah')->default(0);
            $table->integer('penghasilan_ibu')->default(0);
            $table->string('alamat_ortu')->nullable();
            $table->string('kota_ortu', 100)->nullable();
            $table->string('kode_pos_ortu', 6)->nullable();
            $table->char('id_kabupaten_ortu', 10)->default('0');
            $table->char('id_prov_ortu', 2)->default('0');
            $table->char('id_kab_ortu', 4)->default('0');
            $table->char('id_kec_ortu', 6)->default('0');
            $table->char('id_kel_ortu', 10)->nullable()->default('0');
            $table->string('negara_ortu', 50)->nullable();
            $table->string('telpon_ortu', 50)->nullable();
            $table->string('handphone_ortu', 50)->nullable();
            $table->string('email_ortu', 100)->nullable();
            $table->string('sekolah_asal', 100)->nullable();
            $table->tinyInteger('id_jenis_sekolah')->nullable();
            $table->string('kota_sekolah', 50)->nullable();
            $table->integer('id_jurusan_sekolah')->nullable();
            $table->float('nilai_sekolah')->nullable();
            $table->date('tgl_lulus')->nullable()->comment('Lulus dari perguruan tinggi');
            $table->decimal('IPK', 4)->default(0);
            $table->integer('status_bintalfisdis')->default(0);
            $table->string('foto', 25)->default('blm_ada_foto.jpg');
            $table->smallInteger('id_verifikasi')->default(0);
            $table->text('ket_ktm')->nullable();
            $table->string('foto_ktp', 25)->default('blm_ada_foto.jpg');
            $table->string('foto_ijasah', 25)->default('blm_ada_foto.jpg');
            $table->string('foto_transkip', 25)->default('blm_ada_foto.jpg');
            $table->char('foto_status', 1)->default('B')->comment('B:Belum A:Sudah Aktif');
            $table->string('foto_kk', 25)->default('blm_ada_foto.jpg');
            $table->char('kk_status', 1)->default('B');
            $table->string('foto_ak', 25)->default('blm_ada_foto.jpg');
            $table->char('akta_status', 1)->default('B');
            $table->string('ket')->default('0');
            $table->smallInteger('jml_tanggungan_sekolah_sd')->default(0);
            $table->smallInteger('jml_tanggungan_sekolah_smp')->default(0);
            $table->smallInteger('jml_tanggungan_sekolah_sma')->default(0);
            $table->smallInteger('jml_tanggungan_kuliah')->default(0);
            $table->integer('tagihan_pdam')->default(0);
            $table->integer('tagihan_pln')->default(0);
            $table->string('status_rumah', 15)->default('0');
            $table->string('daya_pln', 10)->default('0');
            $table->string('foto_pln', 25)->default('blm_ada_foto.jpg');
            $table->string('foto_pdam', 25)->default('blm_ada_foto.jpg');
            $table->string('foto_gaji', 25)->default('blm_ada_foto.jpg');
            $table->char('pln_status', 1)->default('B');
            $table->char('pdam_status', 1)->default('B');
            $table->char('gaji_status', 1)->default('B');
            $table->smallInteger('pernyataan_status')->default(0);
            $table->string('foto_sehat', 25)->default('blm_ada_foto.jpg');
            $table->string('foto_warna', 25)->default('blm_ada_foto.jpg');
            $table->string('srt_pernyataan', 25)->default('blm_ada_foto.jpg');
            $table->string('almamater', 5)->default('0');
            $table->char('status_entry_data', 1)->default('B');
            $table->char('finalisasi_data', 1)->default('0');
            $table->char('validasi_prodi', 1)->default('0');
            $table->string('bidikmisi', 5)->nullable()->default('0');
            $table->string('id_pembayaran', 15)->default('0');
            $table->string('ukuran_baju', 15)->default('0');
            $table->integer('nilai')->default(0);
            $table->dateTime('tgl_jam')->nullable();
            $table->char('mobile', 1)->nullable();
            $table->smallInteger('id_jenis_tinggal')->nullable()->default(0);
            $table->smallInteger('id_transportasi')->nullable()->default(0);
            $table->text('nama_ktp')->nullable();
            $table->string('no_wa', 50)->nullable();
            $table->string('no_kuota', 50)->nullable();
            $table->date('last_access_kuota')->nullable();
            $table->integer('jml_ukt_cicil')->nullable();
            $table->string('provider', 50)->nullable();
            $table->string('raport', 50)->nullable();
            $table->string('raport2', 50)->nullable();
            $table->string('raport3', 50)->nullable();
            $table->string('raport4', 50)->nullable();
            $table->string('raport5', 50)->nullable();
            $table->string('raport6', 50)->nullable();
            $table->smallInteger('status_lulus')->nullable();
            $table->char('rt_asal', 4)->nullable();
            $table->char('rw_asal', 4)->nullable();
            $table->string('foto_ti_pernyataan', 25)->nullable();
            $table->string('foto_ti_komitmen', 25)->nullable();
            $table->string('foto_gaji_ibu', 25)->nullable();
            $table->string('foto_akta', 25)->nullable();
            $table->string('foto_ukt', 25)->nullable();
            $table->char('status_pernyataan', 1)->nullable();
            $table->smallInteger('status_kip')->nullable();
            $table->smallInteger('id_penghasilan_ayah')->nullable();
            $table->smallInteger('id_penghasilan_ibu')->nullable();
            $table->smallInteger('id_rumah_sakit')->nullable();
            $table->smallInteger('id_penyakit')->nullable();
            $table->string('no_kip', 25)->nullable();
            $table->string('no_ujian', 25)->nullable();
            $table->string('foto_cicil', 25)->nullable();
            $table->string('foto_ukt_bintalfisdis', 25)->nullable();
            $table->string('foto_skhu', 25)->nullable();
            $table->string('foto_sktl', 25)->nullable();
            $table->string('kartu_peserta', 25)->nullable();
            $table->string('formulir_kip', 25)->nullable();
            $table->string('kip_kks', 25)->nullable();
            $table->string('rekom_dinsos', 25)->nullable();
            $table->string('sktm', 25)->nullable();
            $table->string('penghasilan_kelurahan', 25)->nullable();
            $table->string('id_registrasi_cicil', 25)->nullable();
            $table->string('mobile_cicil', 25)->nullable();
            $table->date('tgl_lahir_ayah')->nullable();
            $table->date('tgl_lahir_ibu')->nullable();
            $table->tinyInteger('prodi1')->nullable();
            $table->tinyInteger('prodi2')->nullable();
            $table->string('foto_bintalfisdis', 25)->nullable();
            $table->char('ukt', 1)->nullable();
            $table->string('hp', 25)->nullable();
            $table->char('c_19', 1)->nullable();
            $table->string('tempat_vaksin')->nullable();
            $table->char('vaksin', 1)->nullable();
            $table->date('tgl_vaksin')->nullable();
            $table->date('tgl_terpapar_c19')->nullable();
            $table->char('vaksin2', 1)->nullable();
            $table->date('tgl_vaksin2')->nullable();
            $table->string('tempat_vaksin2')->nullable();
            $table->string('nama_vaksin')->nullable();
            $table->char('status_entry', 1)->nullable();
            $table->char('status_profile', 1)->default('0');
            $table->text('ket_pemeriksa')->nullable();
            $table->smallInteger('id_pemeriksa')->default(0);
            $table->string('email_lupa', 100)->default('arifbjm.mmm@gmail.com');
            $table->smallInteger('id_susulan_verifikasi')->default(0);
            $table->text('link_video')->nullable();
            $table->text('ket_video')->nullable();
            $table->char('status_video', 1)->default('0');
            $table->text('link_ppdkti')->nullable();
            $table->char('verifikasi_foto_yudisium', 1)->default('0');
            $table->string('file_ijazah', 50)->nullable();
            $table->string('file_transkrip', 50)->nullable();
            $table->char('rfid', 10)->nullable();
            $table->char('edit', 1)->nullable()->default('0');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('siap_mhs');
    }
};
