name: Deploy API to PBL VPS Mahasiswa 4E

on:
  push:
    branches:
      - main
jobs:
  deploy-to-vps-pbl:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy PBL Mahasiswa 4E
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_KELOMPOK3_4E }}
          script: |
            cd /root/kelompok-3-4e/Backend_PBL
            
            git stash

            git pull origin main
            
            docker compose exec -T php composer install --no-interaction --prefer-dist --optimize-autoloader

            docker compose exec -T php php artisan migrate --force

            docker compose exec -T php php artisan db:seed --force
                        
            docker compose exec -T php php artisan optimize:clear